### ISSUE TITLE
TypeError: Miner.__init__() got an unexpected keyword argument 'config'

### ISSUE THREAD

**Issue by yusufseyrek** [opentensor/prompting#147]
While running the miner script getting the following error:
```
TypeError: Miner.__init__() got an unexpected keyword argument 'config'
```

Script:
```
yusuf@miner:~/tao-mining/prompting$ python3 neurons/miners/zephyr/miner.py --netuid 1 --wallet.name m2 --wallet.hotkey m2h --neuron.model_id HuggingFaceH4/zephyr-7b-beta --axon.port 8890
```

Any python guru here knows why?

**Comment by mccrindlebrian** [comment]
I'm not sure why you would be seeing this error, but I would recommend just starting from scratch. Are you sure that you did `python -m pip install -e . `?

**Comment by mccrindlebrian** [comment]
closing because it's stale.
