### ISSUE TITLE
config parsing error in Zephyr mining py file

### ISSUE THREAD

**Issue by jackieji** [opentensor/prompting#157]
i am running the command from cmd: python neurons/miners/zephyr/miner.py --wallet.name myTaoCold --wallet.hotkey myTaoHot --subtensor.network local --netuid 1 --logging.debug True --neuron.model_id HuggingFaceH4/zephyr-7b-beta --neuron.system_prompt "Hello, I am a chatbot. I am here to help you with your questions." --neuron.max_tokens 64 --neuron.do_sample True --neuron.temperature 0.9 --neuron.top_k 50 --neuron.top_p 0.95 --wandb.on True --wandb.entity sn1 --wandb.project_name miners_experiments --neuron.load_quantized True
I keep getting the error TypeError: Miner.init() got an unexpected keyword argument 'config' in line 50

If i remove the default config argument then i get the error AttributeError: 'NoneType' object has no attribute 'load_quantized'
![Screenshot from 2024-03-14 05-29-57](https://github.com/opentensor/prompting/assets/13640060/0ceef67a-921a-4569-ade1-bbc2fc43b448)
![Screenshot from 2024-03-14 05-16-39](https://github.com/opentensor/prompting/assets/13640060/2166ced2-51bc-4d3e-91fe-8610f89b20fc)

**Comment by jackieji** [comment]
I tried same in other releases and also the latest release still i don't have config variable set from the passed cmd line parameters. All the requirements and libraries have been checked and installed properly.

**Comment by jackieji** [comment]
Getting the same error in other mining files like test, openai, wiki_agentalso. Is it some setting related?

![Screenshot from 2024-03-14 07-39-41](https://github.com/opentensor/prompting/assets/13640060/4ff7a93d-7cf5-4867-acb5-f46625bc1f64)

**Comment by mccrindlebrian** [comment]
This really shouldn't be happening. Are you sure that you're running the repo with the correct dependancies, and nothing is getting messed up with your paths? How did you create your environment? What machines are you using?

**Comment by mccrindlebrian** [comment]
closing because it's stale
