### ISSUE TITLE
Remove unecessary imports for miners

### ISSUE THREAD

**Issue by bkb2135** [opentensor/prompting#172]
Importing prompting is throwing errors for miners because of the angle model and it's required imports. It may be beneficial to not import all of prompting for the spec version.

**Comment by mccrindlebrian** [comment]
@bkb2135 is this done?

**Comment by p-ferreira** [comment]
Considering that everything is now centralized within the prompting package, this shouldn't be a problem anymore. Feel free to reopen the issue in case that's not the correct interpretation of the current state.
